[build]
  base = "/"
  publish = ".next"
  command = "ls -la && npm install && npm run build"

[build.environment]
  NPM_FLAGS = "--no-optional"
  NODE_VERSION = "18.0.0"

[[plugins]]
  package = "@netlify/plugin-nextjs" 